feat(snippet): fix now playing icon color
spicetify/spicetify-marketplace pull request #326
Opened 2022-09-08 17:13 UTC by Tetrax-10

2022-09-22 21:34 UTC, CharlieS1103 approved these changes
LGTM, I think as long as padster has no changes you're good to go.

2022-09-22 23:20 UTC, theRealPadster commented
> LGTM, I think as long as padster has no changes you're good to go.

Lol you guys keep acting like I don't have a pending review with comments ..

2022-09-22 23:32 UTC, theRealPadster requested changes

2022-09-22 23:37 UTC, CharlieS1103 commented
> > LGTM, I think as long as padster has no changes you're good to go.
> 
> Lol you guys keep acting like I don't have a pending review with comments ..

Wait you did? For whatever reason I didn't see that. Unless of course that's a joke in which case I also didn't see that.

2022-09-23 11:58 UTC, Tetrax-10 commented on packages/marketplace/src/resources/snippets.ts
> +    "preview": "resources/assets/snippets/remove-gradient.png",
it works like i just ported it from my theme

2022-09-23 11:58 UTC, Tetrax-10 commented on packages/marketplace/src/resources/snippets.ts
> +    "title": "Fix Liked Button",
when clicking the color will be green this one actually fixes it

2022-09-23 19:20 UTC, theRealPadster commented on packages/marketplace/src/resources/snippets.ts
> +    "title": "Fix Liked Button",
@kyrie25 Didn't you fix this with something in the go file or something? Or am I imagining things?

2022-09-23 23:09 UTC, kyrie25 commented on packages/marketplace/src/resources/snippets.ts
> +    "title": "Fix Liked Button",
I don't remember doing so? The one I fixed was the button color on highlight and pressed.

2022-09-23 23:13 UTC, Tetrax-10 commented on packages/marketplace/src/resources/snippets.ts
> +    "title": "Fix Liked Button",
yeah while clicking liked button that animation color will be fixed by this snippet

2022-09-24 02:08 UTC, CharlieS1103 commented on packages/marketplace/src/resources/snippets.ts
> +    "preview": "resources/assets/snippets/remove-gradient.png",
It does work

2022-09-24 02:56 UTC, theRealPadster commented on packages/marketplace/src/resources/snippets.ts
> +    "title": "Fix Liked Button",
Ahh good stuff 👍

2022-09-24 02:56 UTC, theRealPadster approved these changes

2022-09-24 04:23 UTC, merged