New CSS snippet
spicetify/spicetify-marketplace pull request #371
Opened 2022-11-06 14:13 UTC by MetteDE

Just a simple CSS snippet to hide the liked Songs card in the "Your Library" task, because I often find it useless. Maybe some other people will find this helpful. 

![previews](https://user-images.githubusercontent.com/92314845/200175722-10d3cfa5-6210-418c-8eba-7fb75aec9b27.png)

2022-11-06 14:40 UTC, CharlieS1103 commented
Seems all good to me, is the image alright @theRealPadster

2022-11-06 17:00 UTC, Tetrax-10 commented
its better if you use `collection-collectionEntityHeroCard-likedSongs` instead of `main-heroCard-card`. who knows spotify may add a diff hero card (big card) for events may be.

2022-11-06 17:50 UTC, MetteDE commented
Yea I tried multiple different classes but there was no difference in the outcome so I chose main-heroCard-card because of simplicity

2022-11-06 22:12 UTC, theRealPadster commented
> Seems all good to me, is the image alright @theRealPadster

I'd recommend adding a red x through it, so it's clear it removes that section.

2022-11-06 23:50 UTC, MetteDE commented
Like this? 

![hide-likedSongs-card ](https://user-images.githubusercontent.com/92314845/200202280-dd02e444-ff54-43c3-a3e3-c0fec334badf.png)

2022-11-07 00:47 UTC, theRealPadster commented
Yep that's better 👍

2022-11-07 00:48 UTC, theRealPadster requested changes

2022-11-07 00:48 UTC, theRealPadster commented on packages/marketplace/src/resources/snippets.ts
> +    "preview": "resources/assets/snippets/hide-likedSongs-card.png"
Missing trailing comma

2022-11-07 14:54 UTC, MetteDE commented
Sorry, I have a lot do to in the next few days and kinda new to this github stuff. I hope, its complete now!

2022-11-07 15:13 UTC, theRealPadster requested changes

2022-11-07 15:13 UTC, theRealPadster commented on packages/marketplace/src/resources/snippets.ts
> +  }
I think this is the last change. You should just be able to commit from this suggestion :) 
```suggestion
  },
```

2022-11-07 15:15 UTC, MetteDE commented
Thanks a lot! :D

2022-11-07 16:13 UTC, merged

2022-11-08 03:38 UTC, Tetrax-10 commented
> 

ofcource there wont be any diff. `main-heroCard-card` is a general class name for big cards in your lib. currently there is only 1 hero card which is the liked songs. spotify may include a hero card in future who know.