Use default spotify color fetching
spicetify/spicetify-marketplace pull request #401
Opened 2022-12-10 23:15 UTC by CharlieS1103

2022-12-10 23:16 UTC, CharlieS1103 commented
I have a feeling this is going to bring our package size down substantially as well.

2022-12-11 00:54 UTC, kyrie25 requested changes

2022-12-11 00:54 UTC, kyrie25 commented on src/logic/Utils.ts
> +      const albumArtSrc: string | undefined = albumArt?.src;
Why not use internal functions for this? Especially now you'll only need the URL.
```suggestion
      const albumArt = Spicetify.Player.data?.track?.metadata?.image_xlarge_url;
```

2022-12-11 00:54 UTC, kyrie25 commented on src/logic/Utils.ts
> +  console.log(mainColor);
Cleanup.

2022-12-11 00:54 UTC, kyrie25 commented on src/logic/Utils.ts
> +  console.log(palette);
Cleanup.

2022-12-11 00:54 UTC, kyrie25 commented on src/logic/Utils.ts
> +    let albumArtSrc: string | undefined = albumArt?.src;
Ditto. Looks much cleaner and faster also.
```suggestion
    const albumArt = Spicetify.Player.data?.track?.metadata?.image_xlarge_url;
```

2022-12-11 00:54 UTC, kyrie25 commented on src/logic/Utils.ts
> +      const mainColor : string = await getColorFromImage(albumArtSrc);
```suggestion
      const mainColor: string = await getColorFromImage(albumArtSrc);
```

2022-12-11 10:43 UTC, Tetrax-10 commented
can you expose chroma function to window object? so other themes and extensions dont need import them again
![image](https://user-images.githubusercontent.com/75513645/206899031-26b6cbc4-cd9c-429b-a701-ca73794b6656.png)

2022-12-11 13:48 UTC, theRealPadster commented on src/logic/Utils.ts
> +  const color = await (await Spicetify.colorExtractor(image)).VIBRANT_NON_ALARMING;
Also don't need two awaits

2022-12-11 21:26 UTC, CharlieS1103 commented
Note do not merge till we review #404

2022-12-20 16:05 UTC, CharlieS1103 commented
Is this one good as well?

2022-12-21 22:12 UTC, CharlieS1103 commented
<img width="602" alt="Screen Shot 2022-12-21 at 5 11 34 PM" src="https://user-images.githubusercontent.com/60494758/209012022-8e99da4f-ae58-41c0-a96a-6d1088552f4e.png">
@theRealPadster I don't have this issue

2022-12-22 02:19 UTC, theRealPadster commented
> @theRealPadster I don't have this issue
Yeah my css changes fixed it 👍

2022-12-22 02:21 UTC, theRealPadster approved these changes
Probably good now?

2022-12-24 02:50 UTC, merged