Add Snippet `Pretty Lyrics`
spicetify/spicetify-marketplace pull request #443
Opened 2023-02-26 06:34 UTC by marshiers

Added the snippet entry in `snippets.ts` and a preview image in the `assets` folder under `resources`.

2023-02-26 07:22 UTC, kyrie25 requested changes

2023-02-26 07:22 UTC, kyrie25 commented on src/resources/snippets.ts
> +    "preview": "resources/assets/snippets/prettify-lyrics.png",
Path does not match file name

2023-02-26 11:13 UTC, marshiers commented on src/resources/snippets.ts
> +    "preview": "resources/assets/snippets/pretty-lyrics.png",
Sorry about that, should be fixed now.

2023-02-28 09:00 UTC, kyrie25 approved these changes

2023-02-28 09:00 UTC, merged