Add pl_PL translation
spicetify/spicetify-marketplace pull request #689
Opened 2024-02-17 22:41 UTC by Adamo2499

Menu, sorting options, installed mods
![image](https://github.com/spicetify/spicetify-marketplace/assets/30226946/cd8228c6-49a6-4bbf-8107-4a4aa0425f3b)

Marketplace settings:
![image](https://github.com/spicetify/spicetify-marketplace/assets/30226946/306eb8c2-7455-416e-8451-ffda543d29c8)

2024-02-17 23:05 UTC, rxri requested changes
Why did you use deepl for this if you're native polish speaker 🤦‍♀️ 
![image](https://github.com/spicetify/spicetify-marketplace/assets/9348108/c0097d9b-90ca-46a9-81e4-634898f0eb08)

2024-02-17 23:05 UTC, rxri commented on src/resources/locales/pl.json
> +      "customCSSPlaceholder": "Wprowadź tutaj swój własny CSS! Można go znaleźć w zainstalowanej zakładce zarządzania.",
```suggestion
      "customCSSPlaceholder": "Wprowadź tutaj swój własny CSS! Możesz go znaleźć w zakładce 'Zainstalowane' dla zarządzania.",
```

2024-02-17 23:05 UTC, rxri commented on src/resources/locales/pl.json
> +      "inputPlaceholder": "Skopiuj / wklej tu swoje ustawienia",
```suggestion
      "inputPlaceholder": "Skopiuj/wklej tu swoje ustawienia",
```

2024-02-17 23:05 UTC, rxri commented on src/resources/locales/pl.json
> +      "colorIniEditorPlaceholder": "[your-colour-scheme-name]",
```suggestion
      "colorIniEditorPlaceholder": "[nazwa-twojego-koloru]",
```

2024-02-17 23:05 UTC, rxri commented on src/resources/locales/pl.json
> +      "light": "jasne",
```suggestion
      "light": "jasny",
```

2024-02-17 23:05 UTC, rxri commented on src/resources/locales/pl.json
> +      "wrongLocalTheme": "Ustaw current_theme w config-xpui.ini na \"marketplace\", aby zainstalować motywy za pomocą Marketplace.",
```suggestion
      "wrongLocalTheme": "Ustaw current_theme w config-xpui.ini na \"marketplace\", aby instalować motywy za pomocą Marketplace.",
```

2024-02-17 23:05 UTC, rxri commented on src/resources/locales/pl.json
> +      "markdownParsingError": "Error parsing markdown (HTTP {{status}})",
```suggestion
      "markdownParsingError": "Błąd podczas parsowania markdownu (HTTP {{status}})",
```

2024-02-17 23:05 UTC, rxri commented on src/resources/locales/pl.json
> +      "albumArtBasedColorsMode": "Colour scheme (ColorApi) mode",
```suggestion
      "albumArtBasedColorsMode": "Tryb schematu kolorów (ColorApi)",
```

2024-02-17 23:16 UTC, rxri requested changes
these two as well

2024-02-17 23:16 UTC, rxri commented on src/resources/locales/pl.json
> +      "resetHeading": "Zresetuj",
```suggestion
      "resetHeading": "Reset",
```

2024-02-17 23:16 UTC, rxri commented on src/resources/locales/pl.json
> +      "resetBtn": "$t(settings.resetHeading)",
```suggestion
      "resetBtn": "Zresetuj",
```

2024-02-20 15:00 UTC, theRealPadster approved these changes

2024-02-26 21:04 UTC, rxri commented on src/resources/locales/index.ts
> +  "pl-PL": pl,
```suggestion
  pl,
```
spotify is confusing me

2024-02-26 21:04 UTC, rxri approved these changes

2024-02-26 21:06 UTC, merged