feat(i18n): add japanese translation
spicetify/spicetify-marketplace pull request #736
Opened 2024-04-25 13:11 UTC by HRTK92

2024-04-25 18:04 UTC, rxri requested changes

2024-04-25 18:04 UTC, rxri commented on src/resources/locales/ja.json
> +      "almbumArtColorsModeToolTip": "Monochrome Dark: A colour scheme based directly on the main colour selected, using different shades of the main colour and mixing in greys to create a colour sche
and what about this?

2024-04-26 13:11 UTC, theRealPadster approved these changes

2024-04-26 19:06 UTC, rxri approved these changes

2024-04-26 19:06 UTC, merged